---
application:
  name: "adopetme-frontend"
  project: "adopetme-project"
  organization: "QoveryCommunity"
routers:
- name: "main-adopetme-frontend"
  routes:
  - application_name: "adopetme-frontend"
    paths:
    - "/*"
